import { createElement } from 'lwc';
import Smb_lead_record_edit_form_lds_lwc from 'c/smb_lead_record_edit_form_lds_lwc';

describe('c-smb-lead-record-edit-form-lds-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-smb-lead-record-edit-form-lds-lwc', {
            is: Smb_lead_record_edit_form_lds_lwc
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});