public  class DailyTasks {
    
public static void eatBreakFast(){
    system.debug('Breakfast Done.');

}
public static void  getReady(){
 system.debug('Get Ready.');
}
@future
public static void getBikeServiced(){
    system.debug('Bike Serviced.');
}
public static void attendConferenceCall(){
    system.debug('Attended Conference Call.');
}
public static void PerformTasks(){
    eatBreakFast();
    getReady();
    getBikeServiced();
    attendConferenceCall();



}

    }